name: Validate proxies
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
concurrency:
  group: validate-proxies-${{ github.run_id }}
  cancel-in-progress: false
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --user git-filter-repo
      - name: Run script and update files
        run: |
          python main.py
          git config --global user.name 'Tsprnay'
          git config --global user.email 'abobik3000@icloud.com'
          git add proxies
          git commit -m "Proxies validated on `date +'%Y-%m-%d %H:%M:%S'`"
          git remote add Proxy-Validator https://github.com/Tsprnay/Proxy-Validator.git
          git push --set-upstream Proxy-Validator master --force
